In [1]:
from itertools import permutations
import numpy as np
from Crypto.Util.number import bytes_to_long, long_to_bytes

In [12]:
def det(M):
    def sign(sigma):
        l = 0
        for i in range(5):
            for j in range(i + 1, 5):
                if sigma[i] > sigma[j]:
                    l += 1
        return (-1)**l

    res = 0
    for sigma in permutations([0,1,2,3,4]):
        curr = 1
        for i in range(5):
            curr *= M[sigma[i]][i]
        res += sign(sigma) * curr
    return res


In [13]:
det(M)

0

In [25]:
# x = [1099511627776** 0, 1099511627776 ** 1, 10995116277763 ** 2, 1099511627776 ** 3, 1099511627776 ** 4]
# x = [0, 0, 0, 0, 1]

x = [1]
for i in range(4):
    x.append(x[-1] * 10000000000000)

M = [
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
]

for i in range(5):
    M[i][i] = x[i]

In [30]:
x

[1,
 10000000000000,
 100000000000000000000000000,
 1000000000000000000000000000000000000000,
 10000000000000000000000000000000000000000000000000000]

In [28]:
F = [
    [12, 0, 0, 0, 0],
    [0, 34, 0, 0, 0],
    [0, 0, 56, 0, 0],
    [0, 0, 0, 78, 0],
    [0, 0, 0, 0, 90],
]

In [29]:
R = np.matmul(M, F)
print(R)
print(np.trace(R))

[[12 0 0 0 0]
 [0 340000000000000 0 0 0]
 [0 0 5600000000000000000000000000 0 0]
 [0 0 0 78000000000000000000000000000000000000000 0]
 [0 0 0 0 900000000000000000000000000000000000000000000000000000]]
900000000000078000000000005600000000000340000000000012


In [24]:
long_to_bytes(np.trace(R))

b'Z\x00\x00\x00\x00N\x00\x00\x00\x15\xe0\x00\x00\x00\rB\x00\x00\x00\x02\x04'

In [5]:
b'\xff\xff'

'ffff'

In [6]:
bytes_to_long(b'\xff' * 5)

1099511627775

In [9]:
hex(1099511627776)

'0x100000000000000000000'

In [36]:
res = 4658061070050163852545397042603108131104401578931720504280474484

In [37]:
arr = []
for i in range(5):
    print(res % 10000000000000)
    arr.append(res % 10000000000000)
    res = res // 10000000000000

504280474484
440157893172
426031081311
163852545397
465806107005


In [43]:
s = b''
for i in arr:
    s = s + long_to_bytes(i)

In [44]:
s

b'uiuctf{tr4c1ng_&&_mult5!}'